name: Deploy Angular 20 SSR to Azure App Service (Linux)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  NODE_VERSION: '20.x'
  APP_NAME: testaaifrontend-hzegd8e7a7fhfbe8

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      # Limpia posibles artefactos previos del runner
      - name: Clean Angular cache
        run: rm -rf .angular dist || true

      # Instalamos dependencias, aunque Azure también lo hará (opcional)
      - name: Install deps (CI)
        run: npm ci

      # Iniciamos sesión en Azure con Publish Profile
      - name: Azure login (publish profile)
        uses: azure/login@v2
        with:
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

      # Aquí subimos el código fuente a Azure, NO los artefactos
      - name: Deploy to Azure App Service (Linux)
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.APP_NAME }}
          package: .
        env:
          NODE_ENV: production

      - name: Logout from Azure
        run: az logout || true
